# Generated by Django 5.1.5 on 2025-02-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_refunded_alter_order_status_cancellation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cancellation',
            new_name='CancellationRequests',
        ),
        migrations.RenameIndex(
            model_name='cancellationrequests',
            new_name='orders_canc_created_d93c57_idx',
            old_name='orders_canc_created_c93c64_idx',
        ),
    ]
