# Generated by Django 5.1.5 on 2025-02-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_cancellation_cancellationrequests_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CancellationRequests',
            new_name='CancellationRequest',
        ),
        migrations.RenameIndex(
            model_name='cancellationrequest',
            new_name='orders_canc_created_9449b1_idx',
            old_name='orders_canc_created_d93c57_idx',
        ),
    ]
